### ISSUE TITLE
Method transform should keep all input columns in the result

### ISSUE THREAD

**Issue by olbapjose** [mjuez/approx-smote#1]
Congrats and thanks for making this available in Spark!

I am right now finishing a Pyspark wrapper around your code and I've found that the transform() method only selects the features and the label column:

https://github.com/mjuez/approx-smote/blob/4672945a5cd244b54038b857e09db30f330604ba/src/main/scala/org/apache/spark/ml/instance/ASMOTE.scala#L170

However, the DF returned should contain all the columns of the input DF in order to be consistent with the expected behaviour of all existing Spark transformers. Otherwise, it becomes much more difficult to use in real use cases where you might have a lot of columns in the dataset you need to oversample.

**Comment by mjuez** [comment]
Since I preprocessed all datasets I use for research purposes to have label and features columns, I was not aware that the way I decided to "reorder" the columns for joining datasets, was actually filtering them and thus causing to loose important data.

Thank you for your feedback, hopefully it is solved now.
